name: longvu
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=24.2
  - python=3.10.0
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==1.1.1
      - annotated-types==0.7.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - decord==0.6.0
      - deepspeed==0.14.4
      - einops==0.8.0
      - filelock==3.13.1
      - flash-attn==2.7.0.post2
      - fsspec==2024.2.0
      - grpcio==1.70.0
      - hjson==3.1.0
      - huggingface-hub==0.26.2
      - idna==3.4
      - iopath==0.1.10
      - jinja2==3.1.3
      - markdown==3.7
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - msgpack==1.1.0
      - networkx==3.2.1
      - ninja==1.11.1.3
      - numpy==1.26.3
      - nvidia-ml-py==12.570.86
      - opencv-python==4.10.0.84
      - packaging==24.2
      - pillow==10.2.0
      - portalocker==2.10.1
      - protobuf==5.28.3
      - psutil==6.1.0
      - py-cpuinfo==9.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.28.1
      - safetensors==0.4.5
      - six==1.17.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.19.1
      - torch==2.1.2+cu121
      - torchaudio==2.1.2+cu121
      - torchvision==0.16.2+cu121
      - tqdm==4.67.0
      - transformers==4.42.4
      - triton==2.1.0
      - typing-extensions==4.12.2
      - urllib3==1.26.13
      - werkzeug==3.1.3
